### ISSUE TITLE
Private/Public User Accounts

### ISSUE THREAD

**Issue by abhilashvadnala** [GKV-Newbie/Newbie-REST#1]
- **User Account** can be public or private. This features abstracts the directory of a private user.
- But a user who wants to see a procedure should have permission to access the procedures
- Private user accounts can be requested to follow
    - so that a user can see the procedure groups of another user.
- Public user account's directory structure can be viewed by everyone

**Comment by nihalkondasjsu** [comment]
Not getting to it at the moment
